import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = {
  title: "AI Disclaimer",

  description:
    "Learn about the limitations of AI-generated legal information provided by Shiraz Legal Associates AI Assistant.",

  keywords: [
    "AI Disclaimer",
    "Legal AI",
    "AI Legal Assistant",
    "Pakistan Legal AI",
    "Shiraz Legal Associates AI",
  ],
};
export default function AIDisclaimerPage() {
  return (
    <main>

      {/* Hero */}

      <section className="bg-[#0B1F3A] text-white py-24">
        <div className="max-w-7xl mx-auto px-6 text-center">

          <h1 className="text-5xl font-bold">
            AI Legal Assistant Disclaimer
          </h1>

          <p className="mt-6 text-xl text-gray-300 max-w-3xl mx-auto">
            Please read this disclaimer carefully before using the Shiraz Legal
            Associates AI Legal Assistant.
          </p>

        </div>
      </section>

      {/* Content */}

      <section className="py-20 bg-gray-100">
        <div className="max-w-5xl mx-auto px-6">

          <div className="bg-white rounded-3xl shadow-lg p-10">

            <h2 className="text-3xl font-bold text-[#0B1F3A]">
              General Information Only
            </h2>

            <p className="mt-6 text-gray-600 leading-8">
              The AI Legal Assistant available on this website is intended to
              provide general information about Pakistani law. It is designed
              for educational and informational purposes only.
            </p>

            <h2 className="text-3xl font-bold text-[#0B1F3A] mt-12">
              Not Legal Advice
            </h2>

            <p className="mt-6 text-gray-600 leading-8">
              Responses generated by the AI Legal Assistant should never be
              considered legal advice. Every legal matter is different and
              requires professional evaluation by a qualified advocate.
            </p>

            <h2 className="text-3xl font-bold text-[#0B1F3A] mt-12">
              No Advocate-Client Relationship
            </h2>

            <p className="mt-6 text-gray-600 leading-8">
              Using the AI Legal Assistant does not create an advocate-client
              relationship with Shiraz Legal Associates or any of its legal
              professionals.
            </p>
                        <h2 className="text-3xl font-bold text-[#0B1F3A] mt-12">
              Accuracy of Information
            </h2>

            <p className="mt-6 text-gray-600 leading-8">
              Although we strive to provide accurate and up-to-date information,
              AI-generated responses may occasionally contain inaccuracies,
              omissions or outdated legal information. Laws and legal procedures
              may change over time.
            </p>

            <h2 className="text-3xl font-bold text-[#0B1F3A] mt-12">
              Always Consult a Qualified Advocate
            </h2>

            <p className="mt-6 text-gray-600 leading-8">
              Before making any legal decision or taking legal action, you
              should always consult a licensed advocate who can evaluate your
              specific circumstances and provide professional legal advice.
            </p>

            <h2 className="text-3xl font-bold text-[#0B1F3A] mt-12">
              Limitation of Liability
            </h2>

            <p className="mt-6 text-gray-600 leading-8">
              Shiraz Legal Associates shall not be held responsible for any
              loss, damage or legal consequences resulting from reliance on
              AI-generated responses. Users assume full responsibility for how
              they use the information provided.
            </p>

            <h2 className="text-3xl font-bold text-[#0B1F3A] mt-12">
              Responsible Use
            </h2>

            <ul className="list-disc pl-6 mt-6 text-gray-600 leading-8 space-y-2">
              <li>Use the AI Legal Assistant only for lawful purposes.</li>
              <li>Do not rely solely on AI for legal decisions.</li>
              <li>Verify important legal information with a qualified lawyer.</li>
              <li>Respect all applicable laws and regulations.</li>
            </ul>
                        <h2 className="text-3xl font-bold text-[#0B1F3A] mt-12">
              Contact Information
            </h2>

            <p className="mt-6 text-gray-600 leading-8">
              If you have any questions regarding the AI Legal Assistant or this
              disclaimer, please contact Shiraz Legal Associates directly.
            </p>

            <div className="mt-8 bg-blue-50 rounded-2xl p-6">

              <p className="text-gray-700">
                <strong>📍 Address:</strong><br />
                767/2B Opposite Shafique Plaza,
                Mandian Abbottabad, Pakistan
              </p>

              <p className="mt-4 text-gray-700">
                <strong>📞 Phone:</strong><br />
                0315-5527144<br />
                0300-9119583
              </p>

              <p className="mt-4 text-gray-700">
                <strong>✉️ Email:</strong><br />
                shirazlegalassociates@gmail.com
              </p>

            </div>

            <div className="mt-12 text-center">

              <Link
                href="/contact"
                className="inline-block bg-[#0B1F3A] text-white px-8 py-4 rounded-xl font-semibold hover:bg-blue-800 transition"
              >
                Contact Us
              </Link>

            </div>

          </div>

        </div>
      </section>

    </main>
  );
}